Hidden-Identity-Games/blood-on-the-clocktower

- client/src/GamemasterInGame/GamemasterLanding.tsx
Add custom roles that aren't in json data to character select list on game creation.
> Add unknown custom roles

- client/src/GamemasterInGame/CharacterSelectList.tsx
- client/src/GamemasterInGame/Lobby.tsx
Export id fix, only enable export after roles assigned, only show teams with roles in character select list
> Export id fix, role select team headers cleanup

- client/src/GamemasterInGame/CharacterSelectList.tsx
- client/src/GamemasterInGame/DestructiveButton.tsx
- client/src/GamemasterInGame/GameMasterActions.tsx
- client/src/GamemasterInGame/Lobby.tsx
- client/src/GamemasterInGame/ProblemsPanel.tsx
- client/src/GamemasterInGame/ScriptSelect.tsx
- client/src/PlayerLanding/AddPlayer.tsx
- client/src/PlayerLanding/PlayerWaiting/MeaningfulIcon.tsx
- client/src/PlayerLanding/PlayerWaiting/index.tsx
- client/src/PlayerLanding/index.tsx
- client/src/shared/DialogHeader.tsx
- client/src/shared/PlayerNameButton.tsx
- client/src/shared/RoleIcon.tsx
- client/src/store/secretKey.ts
- server/src/database/gameDB.ts
Cleaned up the UX for the Game Master page a big
> clean up UX

- .husky/pre-commit
- .lintstagedrc
- package.json
- pnpm-lock.yaml
Adds lint-staged which will speed up commit hookmby only running on files that are being comitted.
> setup lint-staged

- client/src/GamemasterInGame/PlayerListComponents/PlayerActions.tsx
- client/src/GamemasterInGame/PlayerListComponents/Selectors/RoleSelect.tsx
- client/src/store/useStore.tsx
- server/src/database/gameDB.ts
- server/src/routes/game.ts
- server/src/types/UnifiedGame.ts
> role-change

- client/src/GamemasterInGame/PlayerListComponents/PlayerNoteInput.tsx
- client/src/GamemasterInGame/ScriptSelect.tsx
- client/src/MainRouter.tsx
- client/src/PlayerLanding/AddPlayer.tsx
Autofocus new player name input, shrink note modal text area
> Purple GM accent and small polish

- client/src/PlayerLanding/PlayerRole.tsx
> Show character name instead of Id on PlayerRole page

- client/src/GamemasterInGame/Lobby.tsx
- client/src/GamemasterInGame/TeamDistributionBar.css
- client/src/GamemasterInGame/TeamDistributionBar.tsx
- client/src/PlayerLanding/PlayerInGame.tsx
- client/src/assets/game_data/gameData.ts
> Show expected team distribution on player scripts display

- client/src/GamemasterInGame/GameMasterActions.tsx
- client/src/GamemasterInGame/GamemasterLanding.tsx
- client/src/PlayerLanding/PlayerRole.tsx
- client/src/PlayerLanding/index.tsx
- client/src/store/actions/playerActions.ts
- server/src/database/gameDB/base.ts
- server/src/database/gameDB/player.ts
- server/src/routes/game.ts
- server/src/testGames.ts
- server/src/types/UnifiedGame.ts
> Players ack roles

- client/src/PlayerLanding/PlayerInGame.tsx
> Player night order sort toggle

- client/src/PlayerLanding/PlayerRole.tsx
- client/src/PlayerLanding/index.tsx
> Reveal ability when revealing role

- client/package.json
- client/src/shared/GameHeader.tsx
- pnpm-lock.yaml
> Add QR Code dialog to game header

- client/src/GamemasterInGame/GameMasterActions.tsx
> Remove unwired first night button from GMActions

- client/src/GamemasterInGame/CharacterSelectList.tsx
- client/src/GamemasterInGame/DestructiveButton.tsx
- client/src/GamemasterInGame/GameMasterActions.tsx
- client/src/GamemasterInGame/Lobby.tsx
- client/src/NewGamePage/index.tsx
- client/src/PlayerLanding/PlayerRoleSelect.tsx
- client/src/store/actions/playerActions.ts
- server/src/database/gameDB/player.ts
- server/src/routes/game.ts
- server/src/types/UnifiedGame.ts
> Duplicate roles (Legion)

- client/package.json
- client/src/GamemasterInGame/CharacterSelectList.tsx
- client/src/GamemasterInGame/DestructiveButton.tsx
- client/src/GamemasterInGame/GameMasterActions.tsx
- client/src/GamemasterInGame/Lobby.tsx
- client/src/NewGamePage/index.tsx
- client/src/PlayerLanding/PlayerRoleSelect.tsx
- client/src/store/actions/playerActions.ts
- pnpm-lock.yaml
- server/src/database/gameDB/player.ts
- server/src/routes/game.ts
- server/src/types/UnifiedGame.ts
Currently will not accommodate duplicate roles (Legion)
> Adding characters to script & multi-role (Legion)

- client/src/shared/GameHeader.tsx
Tapping the header now opens a QR code dialog, with a share button below.
> Clean up share game flow

- client/src/GamemasterInGame/NightOrder.tsx
- client/src/GamemasterInGame/PlayerList.tsx
- client/src/GamemasterInGame/PlayerListComponents/NightReminder.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/AlignmentChangeMessage.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/CharacterSelectedYouMessage.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/DemonMessage.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/MadnessMessage.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/PlayerMessageLink.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/RevealPlayerMessage.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/RevealRoleMessage.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/RevealTeamMessage.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/RevivedMessage.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/RoleChangeMessage.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/index.tsx
- client/src/GamemasterInGame/PlayerListComponents/Selectors/Restrictions.ts
- client/src/GamemasterInGame/PlayerListComponents/Selectors/RoleSelect.tsx
- client/src/GamemasterInGame/PlayerListComponents/Selectors/useDynamicList.tsx
- client/src/MainRouter.tsx
- client/src/assets/game_data/characterData.ts
- server/src/types/PlayerMessageScreen.ts
- server/src/types/Role.ts
Didn't test yet, but swapped em all out.
> add restrictions

- client/src/GamemasterInGame/PlayerList.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerMessage/index.tsx
> Save demon bluffs to grimoire

- client/src/GamemasterInGame/NightOrder.tsx
- client/src/GamemasterInGame/PlayerList.tsx
- client/src/PlayerLanding/PlayerRoleSelect.tsx
- client/src/assets/game_data/scripts.json
- client/src/shared/GameHeader.tsx
> Pad QR Code, lift seat order state for GM

- client/src/GamemasterInGame/Lobby.tsx
- client/src/GamemasterInGame/NightOrder.tsx
- client/src/NewGamePage/index.tsx
- e2es/tests/gmTests.spec.ts
- e2es/tests/playerTests.spec.ts
- e2es/tests/utils.ts
> fix tests for new flow

- client/src/GamemasterInGame/Lobby.tsx
- client/src/GamemasterInGame/NightOrder.tsx
- client/src/GamemasterInGame/PlayerListComponents/PlayerNotes.tsx
- client/src/GamemasterInGame/PlayerLists/GMPlayerList.tsx
- client/src/GamemasterInGame/PlayerLists/NightPlayerList.tsx
- client/src/GamemasterInGame/PlayerLists/SetupPlayerList.tsx
- client/src/PlayerLanding/index.tsx
- client/src/shared/ScriptList.tsx
- client/src/shared/TeamDistributionBar.tsx
- server/src/database/gameDB/player.ts
Someday we'll have version numbers
> Merge to release

- client/src/shared/Grimoire/PlayersInCircle/GMTile.tsx
- client/src/shared/Reminders/ReminderIcon.tsx
- client/tailwind.config.ts
> Color code reminders on GMTile

- client/src/shared/Grimoire/PlayersInCircle/GMTile.tsx
- client/src/shared/Reminders/AddReminder.tsx
- client/src/shared/Reminders/ReminderIcon.tsx
- client/src/store/useStore.tsx
> Allow showing all reminders

- client/src/GMRoute/GMInGame/Tabs/GrimoireTab/GrimoireTab.tsx
- client/src/GMRoute/GMShared/PlayerListComponents/NightAction/KillAction.tsx
- client/src/GMRoute/GMShared/PlayerListComponents/PlayerActions.tsx
- client/src/GMRoute/GMShared/PlayerListComponents/PlayerMessage/ReminderCreator/index.tsx
- client/src/GMRoute/GMShared/RemindersList.tsx
- client/src/design-system/components/button.tsx
- client/src/design-system/components/ui/card.tsx
- client/src/shared/Grimoire/PlayersInCircle/GMTile.tsx
- client/src/shared/Grimoire/PlayersInCircle/SpectatorTile.tsx
- client/src/shared/Reminders/AddReminder.tsx
- client/src/shared/Reminders/ReminderIcon.tsx
- client/src/store/useStore.tsx
- server/src/gameMachine/gameActions.ts
- server/src/gameMachine/gameReducer.ts
- shared/src/gameData/characterData.ts
- shared/src/gameData/gameData.ts
- shared/src/utils/arrayUtils.ts
- shared/src/utils/index.ts
> Honestly, I am just sorry

- client/package.json
- client/src/shared/TeamDistributionBar.tsx
- client/test/PlayerCount.spec.tsx
- client/test/testUtils.tsx
- shared/src/gameData/gameData.ts
Tests for team dsitribution bar (and fix it)
> team distribution bar tests

- client/package.json
- client/src/GMRoute/GMSetup/ScriptSelect.tsx
- client/src/GMRoute/GMShared/PlayerListComponents/PlayerActions.tsx
- client/src/GMRoute/GMShared/PlayerListComponents/PlayerMenuItem.tsx
- client/src/shared/RoleIcon.tsx
- client/test/characterData.spec.ts
- client/test/scriptValidator.spec.ts
- package.json
- server/package.json
- server/src/routes/game.ts
- shared/src/gameData/characterData.ts
- shared/src/gameData/fallOfRome.ts
- shared/src/gameData/modifyJson.cjs
- shared/src/gameData/scripts.ts
- shared/src/shapes/Role.ts
> node 18 release

- client/src/shared/Grimoire/PlayersInCircle/GMTile.tsx
> add always visible role names
